# Hugging Face Spaces deployment (PROJECT_SPEC.md section 8).
#
# Key decisions, all from section 8:
#   * Docker SDK, not the Gradio/Streamlit template — we serve FastAPI *and* Streamlit.
#   * Listens on 7860, which is what Spaces expects.
#   * Training runs at BUILD time (`RUN python run.py`), not at container start. Free-tier
#     Spaces give a writable /tmp only at runtime and no persistent disk, but the build
#     filesystem IS writable — so the trained .pkl artefacts are baked into the image and
#     the running container never needs to write anything.
#   * Installs from requirements-lock.txt so a reviewer's build resolves to the exact
#     versions verified here, not whatever is newest that day (section 6.8).
#   * Runs as non-root uid 1000, matching HF's recommended pattern.
#   * No GPU: XGBoost + SHAP over 15 tabular features runs comfortably on CPU Basic.

FROM python:3.13-slim

# libgomp1 is required by XGBoost's OpenMP runtime; curl is used by HEALTHCHECK.
RUN apt-get update && apt-get install -y --no-install-recommends \
        libgomp1 \
        curl \
    && rm -rf /var/lib/apt/lists/*

# Non-root user, per HF Spaces guidance.
RUN useradd -m -u 1000 user
USER user
ENV HOME=/home/user \
    PATH=/home/user/.local/bin:$PATH \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    MPLCONFIGDIR=/tmp/matplotlib

WORKDIR $HOME/app

# Dependencies first so the layer caches across source edits.
COPY --chown=user requirements-lock.txt ./
RUN pip install --no-cache-dir --user -r requirements-lock.txt

# Source.
COPY --chown=user config.py run.py sample_order.json ./
COPY --chown=user data/ ./data/
COPY --chown=user models/ ./models/
COPY --chown=user evaluate/ ./evaluate/
COPY --chown=user api/ ./api/
COPY --chown=user dashboard/ ./dashboard/

# Train at BUILD time. The image ships with models/*.pkl and outputs/* already produced,
# so the container starts instantly and needs no writable volume. A smaller population is
# used here than the 60k default to keep Space builds inside their time budget; the
# committed model card is generated by a full local `python run.py`.
ENV N_CUSTOMERS=40000
RUN python run.py

EXPOSE 7860

HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
    CMD curl -fsS http://localhost:7860/health || exit 1

# Serve the API on 7860. The Streamlit dashboard is run locally for the demo:
#   streamlit run dashboard/app.py
# A single Space port cannot serve both, and the API is the deliverable a reviewer will
# want to hit directly. To ship the dashboard on the Space instead, replace the CMD with:
#   CMD ["streamlit","run","dashboard/app.py","--server.port=7860","--server.address=0.0.0.0"]
CMD ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "7860"]
